version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1228
      POSTGRES_DB: sistema
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  wildfly:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      JAVA_OPTS: "-Djboss.bind.address=0.0.0.0"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/log

volumes:
  pgdata:
