version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1228
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
  
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes: 
      - ./logs:/app/logs

